# These settings are synced to GitHub by https://probot.github.io/apps/settings/

labels:
  - name: c-all
    color: '#5319E7'
    description: Affects the project as whole

  - name: c-gateway
    color: '#5319E7'
    description: Affects the gateway crate

  - name: c-transport
    color: '#5319E7'
    description: Affects the transport crate

  - name: c-util
    color: '#5319E7'
    description: Affects the util crate

  - name: t-dependencies
    color: '#0052CC'
    description: A change in the dependencies

  - name: t-fix
    color: '#B60205'
    description: Fixes a bug

  - name: t-feature
    color: '#FBCA04'
    description: Introduces a new feature

  - name: t-enhancement
    color: '#006B75'
    description: Improves an existing feature

  - name: t-chore
    color: '#F9D0C4'
    description: Changes that are not features or bug fixes

  - name: t-refactor
    color: '#E99695'
    description: Refactor internals without introducing new feature

  - name: t-actions
    color: '#552F2D'
    description: Changes to the Github Actions
